# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Post.create(
[
    {
      title: "nec dui nunc mattis enim ut",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Id donec ultrices tincidunt arcu non sodales neque. Aliquet nibh praesent tristique magna. Non quam lacus suspendisse faucibus interdum. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Neque egestas congue quisque egestas diam in arcu cursus. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Urna molestie at elementum eu. Integer enim neque volutpat ac. Interdum varius sit amet mattis vulputate enim. Purus semper eget duis at tellus at. Tristique magna sit amet purus gravida quis blandit turpis cursus. Sodales neque sodales ut etiam sit. Sit amet mauris commodo quis imperdiet massa. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Massa enim nec dui nunc mattis enim. Vitae justo eget magna fermentum iaculis. Morbi tincidunt ornare massa eget egestas purus."
    },
    {
      title: "sollicitudin nibh sit amet commodo nulla",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Id donec ultrices tincidunt arcu non sodales neque. Aliquet nibh praesent tristique magna. Non quam lacus suspendisse faucibus interdum. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Neque egestas congue quisque egestas diam in arcu cursus. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Urna molestie at elementum eu. Integer enim neque volutpat ac. Interdum varius sit amet mattis vulputate enim. Purus semper eget duis at tellus at. Tristique magna sit amet purus gravida quis blandit turpis cursus. Sodales neque sodales ut etiam sit. Sit amet mauris commodo quis imperdiet massa. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Massa enim nec dui nunc mattis enim. Vitae justo eget magna fermentum iaculis. Morbi tincidunt ornare massa eget egestas purus."
    },
    {
      title: "nec ultrices dui sapien eget mi",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Id donec ultrices tincidunt arcu non sodales neque. Aliquet nibh praesent tristique magna. Non quam lacus suspendisse faucibus interdum. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Neque egestas congue quisque egestas diam in arcu cursus. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Urna molestie at elementum eu. Integer enim neque volutpat ac. Interdum varius sit amet mattis vulputate enim. Purus semper eget duis at tellus at. Tristique magna sit amet purus gravida quis blandit turpis cursus. Sodales neque sodales ut etiam sit. Sit amet mauris commodo quis imperdiet massa. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Massa enim nec dui nunc mattis enim. Vitae justo eget magna fermentum iaculis. Morbi tincidunt ornare massa eget egestas purus."
    },
    {
      title: "facilisis volutpat est velit egestas dui",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Id donec ultrices tincidunt arcu non sodales neque. Aliquet nibh praesent tristique magna. Non quam lacus suspendisse faucibus interdum. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Neque egestas congue quisque egestas diam in arcu cursus. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Urna molestie at elementum eu. Integer enim neque volutpat ac. Interdum varius sit amet mattis vulputate enim. Purus semper eget duis at tellus at. Tristique magna sit amet purus gravida quis blandit turpis cursus. Sodales neque sodales ut etiam sit. Sit amet mauris commodo quis imperdiet massa. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Massa enim nec dui nunc mattis enim. Vitae justo eget magna fermentum iaculis. Morbi tincidunt ornare massa eget egestas purus."
    },
    {
      title: "malesuada pellentesque elit eget gravida cum",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Id donec ultrices tincidunt arcu non sodales neque. Aliquet nibh praesent tristique magna. Non quam lacus suspendisse faucibus interdum. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Neque egestas congue quisque egestas diam in arcu cursus. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Urna molestie at elementum eu. Integer enim neque volutpat ac. Interdum varius sit amet mattis vulputate enim. Purus semper eget duis at tellus at. Tristique magna sit amet purus gravida quis blandit turpis cursus. Sodales neque sodales ut etiam sit. Sit amet mauris commodo quis imperdiet massa. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Massa enim nec dui nunc mattis enim. Vitae justo eget magna fermentum iaculis. Morbi tincidunt ornare massa eget egestas purus."
    },
    {
      title: "velit ut tortor pretium viverra suspendisse",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Id donec ultrices tincidunt arcu non sodales neque. Aliquet nibh praesent tristique magna. Non quam lacus suspendisse faucibus interdum. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Neque egestas congue quisque egestas diam in arcu cursus. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Urna molestie at elementum eu. Integer enim neque volutpat ac. Interdum varius sit amet mattis vulputate enim. Purus semper eget duis at tellus at. Tristique magna sit amet purus gravida quis blandit turpis cursus. Sodales neque sodales ut etiam sit. Sit amet mauris commodo quis imperdiet massa. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Massa enim nec dui nunc mattis enim. Vitae justo eget magna fermentum iaculis. Morbi tincidunt ornare massa eget egestas purus."
    }
])